//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public int ideaID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int categoryID { get; set; }
        public int imageID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Image Image { get; set; }
    }
}
